CC := clang
CFLAGS := -Wall -std=c17

all: ej3 run

ej1:
	$(CC) ej1.c -o examen1 $(CFLAGS)

ej2:
	$(CC) ej2.c -o examen2 $(CFLAGS)

ej3:
	$(CC) ej3.c -o examen3 $(CFLAGS)
run:
	./examen3

clean:
	-rm examen3
