-- DIFICULTAD B
-- T07.001- Crea las siguientes tablas:
CREATE TABLE TA 
(
	a int,
	b int,
	PRIMARY KEY (a)
);
CREATE TABLE TB
(
	c int,
	d int,
	PRIMARY KEY (c),
	FOREIGN KEY (d) REFERENCES TA(a) 
		ON DELETE CASCADE ON UPDATE CASCADE 
);
CREATE TABLE TC
(
	e int,
	f int,
	PRIMARY KEY (e),
	FOREIGN KEY (f) REFERENCES TB(c)
		ON DELETE CASCADE ON UPDATE CASCADE
);
-- T007.002 Insertar los siguientes datos.
INSERT INTO TA VALUES (1, 10);
INSERT INTO TA VALUES (2, 20);
INSERT INTO TA VALUES (3, 30);
INSERT INTO TB VALUES (100, 1);
INSERT INTO TB VALUES (200, 1);
INSERT INTO TB VALUES (300, 2);
INSERT INTO TB VALUES (400, NULL);
INSERT INTO TC VALUES (1000, 100);
INSERT INTO TC VALUES (2000, 100);
INSERT INTO TC VALUES (3000, NULL);
